basePath: /
definitions:
  server.Req:
    properties:
      options:
        additionalProperties: true
        type: object
      url:
        type: string
    type: object
  server.Res:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
host: localhost:6664
info:
  contact: {}
  description: "" 
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: SCANT3R API
  version: "0.8 Beta"
paths:
  /scan/:
    get:
      consumes:
      - application/json
      description: get the output of all modules
#      parameters:
#      - description: json data
#        in: body
#        name: data
#        required: true
#        schema:
#          $ref: '#/definitions/server.Req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
#          schema:
#            $ref: '#/definitions/server.Res'
      summary:  output
  /scan/{scanid}:
    post:
      consumes:
      - application/json
      description: add scan process
      parameters:
      - description: "" 
        in: path
        name: scanid
        required: true
        type: string
      - description: json data
        in: body
        name: url
        required: true
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Res'
      summary: scan
  /scans:
    get:
      consumes:
      - application/json
      description: show scan list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: scan
swagger: "2.0"
